config/routes.rb
FreeFoodUmn::Application.routes.draw do

  get '/admins/sign_up' => redirect('/')
  get '/admins/password/new' => redirect('/')

  resources :events

  devise_for :admins
  match '/admin' => "admin#index"

  devise_for :organizations
  match '/create_event' => 'events#create_event_from_session_stored_params'

  root :to => "application#index"
  match '/join_us' => "pages#join_us"

  match '/view_by_month' => 'date_view#view_by_month'
  match '/month/:month/year/:year' => "date_view#view_by_month"
  match '/view_by_week' => "date_view#view_by_week", :as => 'root'
  match '/view_by_week/:year/:month/:day' => "date_view#view_by_week"
  match '/view_by_list' => 'date_view#view_by_list'
  match '/view_by_list/xml' => 'date_view#view_by_list_xml'

  match '/mobile' => "date_view#mobile"
  match '/mobile/previous/:n' => "date_view#mobile"
  match '/mobile/next/n' => "date_view#mobile"

  match '/admin_approve_event/:id' => "admin#admin_approve_event"
  match '/admin_approve_organization/:id' => "admin#admin_approve_organization"

  devise_scope :organization do
    match '/organizations/signout' => 'devise/sessions#destroy'
  end
  devise_scope :admin do
    match '/admins/signout' => 'devise/sessions#destroy'
  end
  match '/delete/event/:id' => "events#destroy"

  match '/blog' => 'blog#index'
  match '/parking' => 'blog#parking'

end

app/views/admin/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Description</th>
    <th>Date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    
    <td id="approve<%= event.id %>">
    <% if event.approved_by_admin == false %>
      <a id="admin_approve_event_<%= event.id %>" class="admin_approve_event" value="<%= event.id %>">approve</a>
    <% else %>
    </td>

    <% end %>
    <td><%= event.name %></td>
    <td><%= event.description %></td>
    <td><%= event.date %></td>
    <td><%= event.end_date %></td>
    <td><%= link_to 'Show', event %>&nbsp;</td>
    <td><%= link_to 'Edit', edit_event_path(event) %>&nbsp;</td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Destroy', "/delete/event/#{event.id}", confirm: 'Are you sure?' %></td>
  </tr>
<% end %>
</table>

<br />


<table>
  <tr>
    <td colspan="2">
      <h1>Organizations</h1>
    </td>
  </tr>
  <tr>
    <td></td>
    <td>name</td>
    <td>email</td>
  </tr>
  <% @organizations.each do |organization| %>
  <tr>
    
    <td id="approve_organization_td_<%= organization.id %>">
    <% if organization.approved_by_admin == false %>
      <a id="admin_approve_organization_<%= organization.id %>" class="admin_approve_organization" value="<%= organization.id %>">approve</a>
    <% end %>
    </td>
    
    <td><%= organization.name %></td>
    <td><%= organization.email %></td>
  </tr>
  <% end %>
</table>
<br />

<%= link_to 'New Event', new_event_path %>

<script type="text/javascript">
  $(".admin_approve_event").click(function() {
  id = $(this).attr('value');
  $.get("/admin_approve_event/"+id,
   function(data){
   $('#approve'+id).html('');
   });
  });

  $(".admin_approve_organization").click(function() {
  id = $(this).attr('value');
  $.get("/admin_approve_organization/"+id,
   function(data){
   $('#approve_organization_td_'+id).html('');
   });
  });

</script>