config/routes.rb
FreeFoodUmn::Application.routes.draw do

  get '/admins/sign_up' => redirect('/')
  get '/admins/password/new' => redirect('/')

  resources :events

  devise_for :admins
  match '/admin' => "admin#index"

  devise_for :organizations
  match '/create_event' => 'events#create_event_from_session_stored_params'

  root :to => "application#index"
  match '/join_us' => "pages#join_us"

  match '/view_by_month' => 'date_view#view_by_month'
  match '/month/:month/year/:year' => "date_view#view_by_month"
  match '/view_by_week' => "date_view#view_by_week", :as => 'root'
  match '/view_by_week/:year/:month/:day' => "date_view#view_by_week"
  match '/view_by_list' => 'date_view#view_by_list'
  match '/view_by_list/xml' => 'date_view#view_by_list_xml'

  match '/mobile' => "date_view#mobile"
  match '/mobile/previous/:n' => "date_view#mobile"
  match '/mobile/next/n' => "date_view#mobile"

  match '/admin_approve_event/:id' => "admin#admin_approve_event"
  match '/admin_approve_organization/:id' => "admin#admin_approve_organization"

  devise_scope :organization do
    match '/organizations/signout' => 'devise/sessions#destroy'
  end
  devise_scope :admin do
    match '/admins/signout' => 'devise/sessions#destroy'
  end
  match '/delete/event/:id' => "events#destroy"

  match '/blog' => 'blog#index'
  match '/parking' => 'blog#parking'

end

app/views/layouts/_facebook_api.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=159178234198240";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<div class="footer">
  <%= link_to "Campus groups sign in", "/organizations/sign_in" unless organization_signed_in? %>&nbsp;&nbsp;
  <%= link_to "Contact Us", "#", :id => "opener" %>
  <hr />
  <p>Copyright &copy; 2012 free food umn</p>

	<script type="text/javascript">
	$(document).ready(function() {
		var $dialog = $('<div></div>')
			.html('freefoodumn.com@gmail.com<br /><br />210 Delaware Street SE, Room W116, Minneapolis, MN, 55455<br /><br />507-219-1944')
			.dialog({
				autoOpen: false,
        draggable: false,
        resizeable: false,
				title: 'Contact Us',
			});

		$('#opener').click(function() {
			$dialog.dialog('open');
			// prevent the default action, e.g., following a link
			return false;
		});
	});
	</script>

</div>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34480158-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<div class="row">
  <div class="span4">
    <%= link_to image_tag("logo.png"), root_path %>
  </div>
  <div class="span8">
    <br />
    <%= yield :date_view_ui %>
  </div>
</div>

app/views/layouts/_top_menu.html.erb
<div class="top_menu">

  <%=
    menu_links = [
      {
        link_name: "Home",
        url: root_path,
        regex: /\/(view_by_week|view_by_month|month).*/,
      },
      {
        link_name: "Add event",
        url: "/events/new",
      },
      {
        link_name: "Blog",
        url: "/blog",
      },
    ]
    if admin_signed_in?
      menu_links += [
        {
          link_name: "Admin signout",
          url: "/admins/signout",
        },
        {
          link_name: "Admin",
          url: "/admin",
        }
      ]
    end
    if organization_signed_in?
      menu_links += [
        {
          link_name: "Sign out",
          url: "/organizations/signout",
        },
        {
          link_name: "Edit organization details",
          url: "/organizations/edit",
        }
      ]
    end
    menu_with_link(menu_links)
  %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Free Food Umn</title>
  <%= favicon_link_tag "favicon.ico" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>

  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" %>

  <%= csrf_meta_tags %>
  <%= render 'layouts/google_analytics' %>
</head>
<body>
  <%= render 'layouts/facebook_api' %>
  <div class="top_menu"><%= render "layouts/top_menu" %></div>
  <div class="header"><div class="container"><%= render 'layouts/header' %></div></div>

  <%= yield(:notice) if content_for?(:notice) %>

  <% if content_for?(:skip_having_layout) %>
    <%= content_for?(:content) ? yield(:content) : yield %>
  <% else %>
    <div class="container">
      <% if notice or alert %>
        <br />
        <%= content_tag(:div, notice, :class => 'alert alert-info') unless notice.nil? %>
        <%= content_tag(:div, alert, :class => 'alert alert-error') unless alert.nil? %>
      <% end %>
      <%= content_for?(:content) ? yield(:content) : yield %>
      <br />
      <%= render 'layouts/footer' %>
    </div>
  <% end %>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/date_view_and_ui.html.erb
<% content_for :date_view_ui do %>


<div class="row">
  <div class="span2">
    <%= yield :left_arrow %>
  </div>
  <div class="span4 viewing_mode_description">
    <h2><%= yield :description_of_viewing_mode %></h2><br />
    <%= menu(
      [
        {
          link_name: "view by month",
          url: '/view_by_month',
          regex: /\/(view_by_month|month).*/,
        },
        {
          link_name: "view by week",
          url: '/view_by_week',
          regex: /\/view_by_week.*/,
        },
        {
          link_name: "list",
          url: '/view_by_list',
          regex: /\/view_by_list/,
        },
      ])
    %><br /><br />
    <div class="promotion_message">
    </div>
  </div>
  <div class="span2">
    <%= yield :right_arrow %>
  </div>
</div>
<% end %>

<% content_for :skip_having_layout do %>
true
<% end %>

<% content_for :content do %>
<br />
<div class="container-fluid wrapper">
  <div class="row-fluid">
    <div class="span2" style="text-align: left">
    <% if Rails.env == 'production' %>
        <script type="text/javascript"><!--
        google_ad_client = "ca-pub-4233832583202758";
        /* free food umn skyscraper */
        google_ad_slot = "7657050634";
        google_ad_width = 120;
        google_ad_height = 600;
        //-->
        </script>
        <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        </script>
    <% end %>
    </div>
    <div class="span8">
      <% if notice or alert %>
        <br />
        <%= content_tag(:div, notice, :class => 'alert alert-info') unless notice.nil? %>
        <%= content_tag(:div, alert, :class => 'alert alert-error') unless alert.nil? %>
      <% end %>
      <%= yield :date_view %>
      <br />
      <%= render 'layouts/footer' %>
    </div>
    <div class="span2" style="text-align: right">
    <% if Rails.env == 'production' %>
        <script type="text/javascript"><!--
        google_ad_client = "ca-pub-4233832583202758";
        /* free food umn skyscraper */
        google_ad_slot = "7657050634";
        google_ad_width = 120;
        google_ad_height = 600;
        //-->
        </script>
        <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        </script>
    <% end %>
    </div>
  </div>
</div>
<% end %>

<%= render :template => 'layouts/application' %>